apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloader
spec:
  replicas: 3
  selector:
    matchLabels:
      project: downloader
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        project: downloader
    spec:
      containers:
        - name: downloader
          imagePullPolicy: Always
          image: mahdimehrabi/rb-downloader:v5
          envFrom:
            - configMapRef:
                name: downloaderenv
